version: '3.4'

services:
  database-listener:
    image: database-listener
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_DATABASE: 'ecosystemdb'
    ports:
      - "3307:3306"
    volumes:
      - .:/app
    networks:
      - rede


networks:
  rede:
    external: true
    name: x