version: '3.4'

services:
  database-listener:
    image: database-listener
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_DATABASE: 'ecosystemdb'
    ports:
      - "3306:3306"
    volumes:
      - ./db_data/db_data:/app/db_data